name : "NASA SPACE CONTROL APP"

on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js version 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: installing dependencies
        run: npm install


      - run: npm run build 
        working-directory: client