name : "NASA SPACE CONTROL APP"

on: 
  push: 
    branches: [master]
  pull_requests:
    branches: [master]

jobs:
  build:
   runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: use node.js version 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install
      - run: npm run build --prefix client