name : "NASA SPACE CONTROL APP"
on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env: 
      CI: true
    strategy:
      matrix:
        os-verison: [ubuntu-latest ]
        node-version: [23.x, 24.x]
    runs-on: ${{matrix.os-verison}}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: installing dependencies
        run: npm install
      - run: npm run build 
        working-directory: client